### ISSUE TITLE
Property for relative path

### ISSUE THREAD

**Issue by GeiOoo** [petekinnecom/terminal-command-keys#4]
Im trying to automate running a single Angular test file. 
I need the relative path like its beeing copy from VS Code by right-clicking the file and selecting "Copy Relative Path".

Die only difference to the existing ${relativeFile} is the missing ".\" at the start.

Can you please add this property?

**Comment by petekinnecom** [comment]
Hi @GeiOoo, I'm not sure I'm understanding the issue you're running into.  It sounds like you're requesting that the `${relativeFile}` property have a leading `.` on it, but I'm actually seeing a leading dot in my editor:

Here's a config:

```
    {
        "key": "alt+shift+r",
        "command": "terminalCommandKeys.run",
        "args": {
            "cmd": "echo '${relativeFile}'"
        }
    },
```

And when I use it on an example file, I see this:

```
$ echo './test/extension.test.js'
./test/extension.test.js
```

(here is where the dot is added: https://github.com/petekinnecom/terminal-command-keys/blob/98a52661bc994b524d570b7f7ccbfe20cea8c1fc/extension.js#L55)

Can you give me an example of the behavior that's causing you an issue?

**Comment by GeiOoo** [comment]
Hey, im sry for my bad explanation... The `${relativeFile}` does indeed have starting `.\`. 
For my testing setup i need this path without the starting `.\` for angular/jasmine to fully understand the path in the context of my workspace.

With this config: 
```
    {
        "key": "alt+shift+r",
        "command": "terminalCommandKeys.run",
        "args": {
            "cmd": "echo '${relativeFile}'"
        }
    },
```

I'd like to get this result:
```
$ echo 'test/extension.test.js'
```

Maybe you can add a `${relativeWorkspaceFile}` property which is exactly like `${relativeFile}`but without the starting `.\`.
That would be perfect for my setup :)

**Comment by petekinnecom** [comment]
I see. hmm, I'd prefer not to add an option `${relativeWorkspaceFile}` because both paths should be treated as interchangeable by external systems.  If they are being treated differently in your test suite, I'm wondering if there is a problem with the way your tests are being run. 

If you're on Unix,  you could work around it by editing the file path like this:

```
    {
      "key": "alt+shift+r",
      "command": "terminalCommandKeys.run",
      "args": {
        "cmd": "echo $(cut -c 3- <<< '${relativeFile}')"
      }
    },
```



I'm figuring that you are working on Windows based on the fact that you reference `.\` rather than `./`?  From what I'm reading and my own tests, these two paths should be treated as equivalent on Windows: `.\a\b\c` and `a\b\c`. For example:

```
# cmd.exe

C:\Users\pete> type README.md
{blah blah blah}

C:\Users\pete> type .\README.md
{blah blah blah}
```

So I'm wondering if you can give me some details on why the leading slash is breaking things for you? It would also be helpful if you can find an example of any other tools on Windows where the leading `.\` breaks  things?

**Comment by GeiOoo** [comment]
I think angular/jasmine treats path without a relative indicator (`.\`, `..\`) differently. Even though a relative path does point on the correct file, the teste can't be executed...

![Screenshot 2021-05-15 173254](https://user-images.githubusercontent.com/29431488/118369517-f898eb00-b5a3-11eb-9cd9-fa9df176fbf6.png)
![image](https://user-images.githubusercontent.com/29431488/118369605-41e93a80-b5a4-11eb-99c4-323662a38c4e.png)
As you can see, the only the last command can run this test file.

I dont understand why its a problem to add another property.

**Comment by petekinnecom** [comment]
Hey I lost track of this over time, sorry about that. Adding another option here isn't something I'm planning to do. It seems like a pretty niche problem with the way that angular's test runner operates. If I get reports of this occurring with other projects/frameworks I'll reconsider. To workaround it you can fork the project, remove the period, and install it locally.
